### ISSUE TITLE
Installation issues with IP-Symcon Version 6.4

### ISSUE THREAD

**Issue by F-A-N-2023** [styletronix/SymconAirQ#7] opened 2023-08-27 18:35 UTC
I justed tried to install your nice AirQ implementation in IP-Symcon. 

The installation itself works fine and also the configuration of the IP address and the password. Access is successful..

But "Liste mit Sensoren aktualisieren" results in the following issue:

[](url)https://community.symcon.de/t/airq-luftsensor/134375

**Comment by styletronix** [comment] 2023-08-28 09:53
I will see what's going on and report back.

**Comment by F-A-N-2023** [comment] 2023-08-28 09:58
Hi Andreas,

Thanks in advance. Maybe this will help…

Fatal error: Uncaught TypeError: Argument 1 passed to AirQ::GetFriendlySensorName() must be of the type int, string given, called in C:\ProgramData\Symcon\modules\.store\sxairq\Air Q\module.php on line 780 and defined in C:\ProgramData\Symcon\modules\.store\sxairq\Air Q\module.php:311
Stack trace:
#0 C:\ProgramData\Symcon\modules\.store\sxairq\Air Q\module.php(780): AirQ->GetFriendlySensorName('oxygen')
#1 C:\ProgramData\Symcon\scripts\__generated.inc.php(559): AirQ->UpdateSensorList()
#2 C:\Windows\System32\-(3): SXAIRQ_UpdateSensorList(21687)
#3 {main}
  thrown in C:\ProgramData\Symcon\modules\.store\sxairq\Air Q\module.php on line 311


See you,
Achim

**Comment by styletronix** [comment] 2023-08-28 10:05
You may try to uninstall the Version from the Store and install the GitHub version to see if the newer version has the same error.

To do this go to Kerninstanzen -> Module and add https://github.com/styletronix/SymconAirQ as new module. This is a more recent version than the Store Version.

You may also try to switch to the develop branch. This is the most recent version I am currently working on. But has a high chance of other problems.


As soon as the problem is fixed in the store version, you can easy switch back to it.

**Comment by F-A-N-2023** [comment] 2023-08-28 10:15
Hi Andreas,

I haven’t done that before and I don’t know how to load a GitHub version. Therefor I will wait until the new and actual version is in the IP Symcon store…


Thanks,
Achim

**Comment by styletronix** [comment] 2023-08-28 10:43
I just found the problem. I accidentially declared the sensor as integer but it is actually a string. Should now working with the new version.

**Comment by F-A-N-2023** [comment] 2023-08-28 10:47
Hi Andreas,

klasse! Vielen Dank! Kannst Du die neue Version in den IP Symcon Store laden?


Viele Grüße, 
Achim

**Comment by styletronix** [comment] 2023-08-28 10:52
Ich habe das Modul für den Store eingereicht, es muss dort aber noch durch die Qualitätssicherung von Symcon. Dauert im Regelfall aber max 1 bis 2 Tage bis es freigegeben wird.

**Comment by F-A-N-2023** [comment] 2023-09-21 17:50
Klappt leider noch nicht richtig... Siehe IP-Symcon Forum... Viele Grüße

**Comment by styletronix** [comment] 2023-09-24 07:49
Schaue ich mir so bald wie möglich an.

**Comment by F-A-N-2023** [comment] 2023-09-27 15:46
Wenn ich irgendwie helfen kann, dann lass es mich gerne wissen...

**Comment by F-A-N-2023** [comment] 2023-10-11 11:36
Hi Andreas, did you find some time to look into the problem about the AirQ module in IP Symcon?

**Comment by styletronix** [comment] 2023-10-11 16:15
i will take a look as soon as possible
________________________________

**Comment by styletronix** [comment] 2023-10-16 18:23
Should be fixed in Version 1.5. Just published it to Github. Release in Symcon Store should be available soon

**Closed as completed by styletronix** 2023-10-16 18:23 UTC
Labels: bug
